language: java
jdk:
  - openjdk6

env:
  global:
    - REMOTE_URL=http://fscheffer:634bce7e-ddfd-4ae4-8ea2-c3bac682f796@ondemand.saucelabs.com:80/wd/hub
  matrix:
    - BROWSER=firefox
    - BROWSER=chrome VERSION=36
    - BROWSER=iexplorer
    - BROWSER=safari

addons:
  sauce_connect:
    username: "fscheffer"
    access_key:
      secure: "634bce7e-ddfd-4ae4-8ea2-c3bac682f796"


script: mvn verify -Dtest.remoteUrl=$REMOTE_URL -Dtest.browser=$BROWSER -Dtest.version=$VERSION
